# Generated by Django 5.1.6 on 2025-02-16 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], help_text='Transmission type', max_length=50)),
                ('number_of_seats', models.PositiveIntegerField(help_text='Number of seats in the car')),
                ('number_of_baggages', models.PositiveIntegerField(help_text='Number of baggages the car can accommodate')),
                ('number_of_doors', models.PositiveIntegerField(help_text='Number of doors in the car')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], help_text='Fuel type', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Anonymous', max_length=100)),
                ('customer_email', models.EmailField(default='anonymous@example.com', max_length=254)),
                ('customer_phone', models.CharField(default='0000000000', max_length=20)),
                ('booking_start', models.DateTimeField(default=django.utils.timezone.now, help_text='Start date and time of the rental period')),
                ('booking_end', models.DateTimeField(default=django.utils.timezone.now, help_text='End date and time of the rental period')),
                ('pickup_location', models.CharField(help_text='Pickup location for the rental', max_length=255)),
                ('dropoff_location', models.CharField(help_text='Return location for the rental', max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.car')),
            ],
        ),
    ]
